name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.8

      - name: Change to Terraform Directory
        run: chdir ./terraform


      - name: Terraform Init
        run: terraform init
          working

      - name: Terraform Plan
        run: terraform plan -out=tfplan


      - name: Request Approval
        id: approval
        run: echo "::set-output name=approved::true"
        if: github.event_name == 'push'

      - name: Manual Approval
        if: steps.approval.outputs.approved == 'true'
        run: |
          echo "Deployment Approved. Proceeding with Terraform Apply."

      - name: Terraform Apply
        if: steps.approval.outputs.approved == 'true'
        run: terraform apply tfplan
